 Ask a question: https://github.com/mrdbourke/pytorch-...
🔗 Course materials online: https://learnpytorch.io

Creating Tensors

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#scalar
scalar = torch.tensor(8)
scalar.ndim

0

In [ ]:
scalar.item()

8

In [ ]:
Matrix=torch.tensor([[6,8],[4,10]])

In [ ]:
Matrix.size()

torch.Size([2, 2])

In [ ]:
Matrix.ndim

2

In [ ]:
Tensor=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [ ]:
Tensor.ndim

3

In [ ]:
Tensor.size()

torch.Size([2, 3, 3])

In [ ]:
Tensor[1]

tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])

In [ ]:
Tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
Matrix1=torch.tensor([[[1,2,3]],[[4,5,6]],[[7,8,9]]])
Matrix1.size()

torch.Size([3, 1, 3])

In [ ]:
import torch
random_tensor=torch.rand(size=(3,4))
random_tensor

tensor([[0.6658, 0.6957, 0.6550, 0.9369],
        [0.0692, 0.9228, 0.4482, 0.8549],
        [0.4565, 0.0947, 0.3717, 0.7764]])

In [ ]:
range_0to10=torch.arange(start=0,end=10,step=1)
range_0to10

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
tensor_like=torch.ones_like(input=range_0to10)
tensor_like

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
import torch

In [ ]:
float16_tensor=torch.tensor([1.0,2.0,3.0],
                            dtype=torch.half)
float16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [ ]:
float32_tensor=torch.tensor([1.0,2.0,3.0],
                            dtype=torch.float)
float32_tensor

tensor([1., 2., 3.])

In [ ]:
float32_tensor*float16_tensor

tensor([1., 4., 9.])

In [ ]:
(float32_tensor*float16_tensor).dtype

torch.float32

In [ ]:
int32_tensor=torch.tensor([1,2,3],
                            dtype=torch.int32)
float32_tensor

tensor([1., 2., 3.])

In [ ]:
(float32_tensor/int32_tensor)

tensor([1., 1., 1.])

In [ ]:
random_tensor=torch.rand(size=(6,6))
random_tensor

tensor([[0.3387, 0.8982, 0.8941, 0.7552, 0.0736, 0.4269],
        [0.8126, 0.5858, 0.0276, 0.6173, 0.0032, 0.5532],
        [0.5033, 0.0606, 0.3383, 0.2737, 0.0124, 0.0910],
        [0.5358, 0.6127, 0.6276, 0.8392, 0.7530, 0.8062],
        [0.0964, 0.6630, 0.7886, 0.6321, 0.3332, 0.9829],
        [0.2464, 0.0104, 0.9634, 0.4086, 0.6884, 0.6773]])

In [ ]:
print(f"tensor type :{random_tensor.dtype}",f"tensor shape : {random_tensor.shape}",f"tensor device : {random_tensor.device}")

tensor type :torch.float32 tensor shape : torch.Size([6, 6]) tensor device : cpu


In [ ]:
big_random_tensor=torch.rand(size=(2,2))
big_random_tensor=big_random_tensor*100
big_random_tensor

tensor([[59.8175, 96.6224],
        [11.6751, 29.0322]])

In [ ]:
big_random_tensor[1][0]*100

tensor(1167.5138)

In [ ]:
big_random_tensor+10

tensor([[ 69.8175, 106.6224],
        [ 21.6751,  39.0322]])

In [ ]:
big_random_tensor

tensor([[59.8175, 96.6224],
        [11.6751, 29.0322]])

In [ ]:
big_random_tensor*big_random_tensor

tensor([[3578.1362, 9335.8955],
        [ 136.3088,  842.8687]])

In [ ]:
torch.matmul(big_random_tensor,big_random_tensor)

tensor([[4706.2163, 8584.8770],
        [1037.3328, 1970.9489]])

In [ ]:
import torch
mat_333=torch.rand(size=(3,3,3))
mat_333

tensor([[[0.1157, 0.3015, 0.0846],
         [0.7446, 0.4724, 0.2597],
         [0.9297, 0.6213, 0.6826]],

        [[0.7623, 0.0868, 0.9489],
         [0.7907, 0.9729, 0.2808],
         [0.2506, 0.2328, 0.2200]],

        [[0.9860, 0.5945, 0.2092],
         [0.9062, 0.2649, 0.4000],
         [0.4851, 0.4103, 0.0927]]])

In [ ]:
import torch
transpose_example1 = torch.rand(size=(2,4))
transpose_example2 = torch.rand(size=(2,4))
transpose_example1@transpose_example2

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x4 and 2x4)

In [ ]:
transpose_example2=transpose_example2.T

In [ ]:
transpose_example2

In [ ]:
transpose_example1@transpose_example2

In [ ]:
import torch
sum_n=torch.rand(size=(3,3,3),
                 dtype=torch.float32)
print(sum_n.argmax())
print(sum_n.argmin())
print(torch.sum(sum_n))


In [ ]:
sum_n

In [ ]:
import torch
x=torch.arange(0.01,0.50,0.17)
z=x.reshape(1,3)
z

In [ ]:
x_view=x.view(1,7)
x_view

In [ ]:
x_view[0][0]=1
x_view

In [ ]:
z

In [ ]:
x_stacked=torch.stack([x,x,x,x,x],dim=0)

In [ ]:
x_stacked

In [ ]:
x=torch.zeros(2,2,3,4,5)
x

tensor([[[[[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]]],


         [[[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]]]],



        [[[[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0.],
           [0., 0., 0.,

In [ ]:
y=torch.squeeze(x)
y.size()

torch.Size([2, 2, 3, 4, 5])

In [ ]:
x=torch.zeros(1,9)
y=x.squeeze()
print(y)
z=y.unsqueeze(dim=1)
print(z)
z=y.unsqueeze(dim=0)
z


tensor([0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])


tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
x_original = torch.rand(size=(224, 224, 3))#(height,width,colour channel)
x_permuted = x_original.permute(2,0,1)#(colour channel,height,width)
print(f"x_permuted.shape:{x_permuted.shape}")
print(f"x_original.shape:{x_original.shape}")


x_permuted.shape:torch.Size([3, 224, 224])
x_original.shape:torch.Size([224, 224, 3])


In [ ]:
x_permuted[0,0,0] = 0.2804

In [ ]:
x_original[0,0,0]

tensor(0.2804)

In [ ]:
x=torch.arange(1,10)
y=x.reshape(3,3)
y

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
y[0,1]

tensor(2)

In [ ]:
y[2,2]

tensor(9)

In [ ]:
y[:,2]

tensor([3, 6, 9])

In [ ]:
import torch
torch.manual_seed(22)
random_tensor_A=torch.rand(3,4)
torch.manual_seed(22)
random_tensor_B=torch.rand(3,4)
print(random_tensor_A==random_tensor_B)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
import torch
torch.cuda.is_available()

True

In [1]:
import torch
device="cuda" if torch.cuda.is_available() else "cpu"
tensor=torch.tensor([1,2,3])
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [2]:
tensor_1=tensor.to(device)
tensor_1

tensor([1, 2, 3], device='cuda:0')

In [3]:
tensor_1.device

device(type='cuda', index=0)